package mocks

import db "github.com/DanielDanteDosSantosViana/swplanets/internal/platform/db"
import mock "github.com/stretchr/testify/mock"

// DataLayer is an autogenerated mock type for the DataLayer type
type DataLayer struct {
	mock.Mock
}

// C provides a mock function with given fields: name
func (_m *DataLayer) C(name string) db.Collection {
	ret := _m.Called(name)

	var r0 db.Collection
	if rf, ok := ret.Get(0).(func(string) db.Collection); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(db.Collection)
		}
	}

	return r0
}
