// Code generated by mockery v1.0.0
package mocks

import db "github.com/DanielDanteDosSantosViana/swplanets/internal/platform/db"
import mock "github.com/stretchr/testify/mock"

// Session is an autogenerated mock type for the Session type
type Session struct {
	mock.Mock
}

// Clone provides a mock function with given fields:
func (_m *Session) Clone() db.Session {
	ret := _m.Called()

	var r0 db.Session
	if rf, ok := ret.Get(0).(func() db.Session); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(db.Session)
		}
	}

	return r0
}

// Close provides a mock function with given fields:
func (_m *Session) Close() {
	_m.Called()
}

// DB provides a mock function with given fields: name
func (_m *Session) DB(name string) db.DataLayer {
	ret := _m.Called(name)

	var r0 db.DataLayer
	if rf, ok := ret.Get(0).(func(string) db.DataLayer); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(db.DataLayer)
		}
	}

	return r0
}

// Ping provides a mock function with given fields:
func (_m *Session) Ping() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
